import { type ProviderName } from '../types/index.js';

export interface ProviderEntry {
  id: ProviderName;
  label: string;
  description: string;
  color: string;
  tags: string[];
  keyLabel?: string;
  keyUrl?: string;
  envVar?: string;
  noKeyNeeded?: boolean;
  oauthFlow?: boolean;
  extraNote?: string;
}

export const PROVIDER_REGISTRY: ProviderEntry[] = [
  {
    id: 'opencode-zen',
    label: 'OpenCode Zen',
    color: '#00E5FF',
    description: 'Free AI gateway — Kimi, MiniMax, Trinity and more at zero cost',
    tags: ['free', 'gateway', 'coding'],
    keyLabel: 'ACCESS_KEY',
    keyUrl: 'opencode.ai/zen',
    envVar: 'OPENCODE_API_KEY',
  },
  {
    id: 'anthropic',
    label: 'Anthropic',
    color: '#FF00AA',
    description: 'Claude 3.5 Sonnet, Opus — industry-leading reasoning',
    tags: ['premium', 'reasoning', 'coding'],
    keyLabel: 'X-API-KEY',
    keyUrl: 'console.anthropic.com/settings/keys',
    envVar: 'ANTHROPIC_API_KEY',
  },
  {
    id: 'openai',
    label: 'OpenAI',
    color: '#3FB950',
    description: 'GPT-4o, o1, o3-mini — flagship models from OpenAI',
    tags: ['premium', 'flagship'],
    keyLabel: 'BEARER_TOKEN',
    keyUrl: 'platform.openai.com/api-keys',
    envVar: 'OPENAI_API_KEY',
  },
  {
    id: 'google',
    label: 'Google AI Studio',
    color: '#AA00FF',
    description: 'Gemini 2.0 Pro/Flash — up to 2M token context window',
    tags: ['vision', 'long-context'],
    keyLabel: 'API_KEY',
    keyUrl: 'aistudio.google.com/app/apikey',
    envVar: 'GOOGLE_API_KEY',
  },
  {
    id: 'mistral',
    label: 'Mistral AI',
    color: '#BD93F9',
    description: 'Mistral Large, Codestral, Devstral — European open models',
    tags: ['open-weights', 'coding'],
    keyLabel: 'MISTRAL_KEY',
    keyUrl: 'console.mistral.ai/api-keys',
    envVar: 'MISTRAL_API_KEY',
  },
  {
    id: 'openrouter',
    label: 'OpenRouter',
    color: '#00E5FF',
    description: 'Access 200+ models via one key — includes free-tier models',
    tags: ['aggregator', '200+ models'],
    keyLabel: 'OR_API_KEY',
    keyUrl: 'openrouter.ai/keys',
    envVar: 'OPENROUTER_API_KEY',
    extraNote: 'Tip: filter with #free in /model to see zero-cost models',
  },
  {
    id: 'groq',
    label: 'Groq',
    color: '#50FA7B',
    description: 'Ultra-fast LPU inference — Llama, QwQ at blazing speed',
    tags: ['speed', 'lpu'],
    keyLabel: 'GROQ_API_KEY',
    keyUrl: 'console.groq.com/keys',
    envVar: 'GROQ_API_KEY',
  },
  {
    id: 'xai',
    label: 'xAI',
    color: '#FF5555',
    description: "Grok 3, Grok 3 Mini — xAI's reasoning-capable models",
    tags: ['reasoning', 'new'],
    keyLabel: 'XAI_KEY',
    keyUrl: 'console.x.ai',
    envVar: 'XAI_API_KEY',
  },
  {
    id: 'deepseek',
    label: 'DeepSeek',
    color: '#8BE9FD',
    description: 'DeepSeek-V3 and R1 reasoning — exceptional value, low cost',
    tags: ['cheap', 'reasoning'],
    keyLabel: 'DS_API_KEY',
    keyUrl: 'platform.deepseek.com/api_keys',
    envVar: 'DEEPSEEK_API_KEY',
  },
  {
    id: 'perplexity',
    label: 'Perplexity',
    color: '#FFB86C',
    description: 'Sonar models with live web search built in',
    tags: ['search', 'sonar'],
    keyLabel: 'PPLX_KEY',
    keyUrl: 'perplexity.ai/settings/api',
    envVar: 'PERPLEXITY_API_KEY',
  },
  {
    id: 'cerebras',
    label: 'Cerebras',
    color: '#FF00AA',
    description: 'Hardware-accelerated inference — fastest token generation available',
    tags: ['ultra-fast', 'hardware'],
    keyLabel: 'CB_API_KEY',
    keyUrl: 'cloud.cerebras.ai/platform/api_keys',
    envVar: 'CEREBRAS_API_KEY',
  },
  {
    id: 'together',
    label: 'Together AI',
    color: '#6272A4',
    description: 'Multi-model inference — Llama, Qwen, DeepSeek via one API',
    tags: ['aggregator', 'open-weights'],
    keyLabel: 'TOG_KEY',
    keyUrl: 'api.together.xyz/settings/api-keys',
    envVar: 'TOGETHER_API_KEY',
  },
  {
    id: 'github-copilot',
    label: 'GitHub Copilot',
    color: '#3FB950',
    description: 'GPT-4o, Claude, Gemini — via your Copilot subscription (OAuth)',
    tags: ['coding', 'oauth'],
    oauthFlow: true,
    extraNote: 'Requires GitHub Copilot Pro or Enterprise subscription',
  },
  {
    id: 'ollama',
    label: 'Ollama',
    color: '#3FB950',
    description: 'Run open models locally — completely private, no API key needed',
    tags: ['local', 'private'],
    noKeyNeeded: true,
    extraNote: 'Install: ollama.com  |  Pull a model: ollama pull llama3.3',
  },
  {
    id: 'google-vertex',
    label: 'Google Vertex AI',
    color: '#AA00FF',
    description: 'Gemini on GCP — flagship performance with GCP compliance',
    tags: ['enterprise', 'long-context'],
    noKeyNeeded: true,
    extraNote: 'Run: gcloud auth application-default login  |  Set GOOGLE_CLOUD_PROJECT env var',
  },
  {
    id: 'opencode',
    label: 'opencode',
    color: '#00E5FF',
    description: 'opencode.ai gateway — high-throughput access to top models',
    tags: ['gateway', 'high-throughput'],
    keyLabel: 'API_KEY',
    keyUrl: 'opencode.ai',
    envVar: 'OPENCODE_API_KEY',
    extraNote: 'Leave blank to access free models with public access',
  },
  {
    id: 'amazon-bedrock',
    label: 'Amazon Bedrock',
    color: '#FF9900',
    description: 'AWS-managed models — Anthropic Claude and Amazon Nova',
    tags: ['enterprise', 'aws'],
    noKeyNeeded: true,
    extraNote: 'Set AWS_ACCESS_KEY_ID + AWS_SECRET_ACCESS_KEY + AWS_REGION, or use IAM roles',
  },
  {
    id: 'azure',
    label: 'Azure OpenAI',
    color: '#0078D4',
    description: 'OpenAI models on Azure — enterprise-grade deployments',
    tags: ['enterprise', 'azure'],
    keyLabel: 'AZURE_API_KEY',
    keyUrl: 'portal.azure.com',
    envVar: 'AZURE_API_KEY',
    extraNote: 'Also set AZURE_RESOURCE_NAME env var to your Azure resource name',
  },
  {
    id: 'custom' as any,
    label: 'Custom Provider',
    color: '#8C959F',
    description: 'Any OpenAI-compatible API endpoint',
    tags: ['custom', 'openai-compatible'],
    keyLabel: 'CUSTOM_KEY',
    envVar: 'CUSTOM_API_KEY',
    extraNote: 'Switch with: /model custom/http://localhost:8080/v1|model-name',
  },
];
