import type { ProviderName } from '../types/index.js';
import type { ModelEntry, ModelTag } from './registry.js';

const fast = { tags: ['fast'] as ModelTag[] };
const reasoning = { tags: ['reasoning'] as ModelTag[] };

export const openrouterModels: ModelEntry[] = [
  {
    provider: 'openrouter' as ProviderName,
    id: 'anthropic/claude-3.5-sonnet',
    label: 'Claude 3.5 Sonnet (OpenRouter)',
    contextWindow: 200_000,
    inputCostPer1M: 3,
    outputCostPer1M: 15,
    free: false,
  },
  {
    provider: 'openrouter' as ProviderName,
    id: 'anthropic/claude-3-haiku',
    label: 'Claude 3 Haiku (OpenRouter)',
    contextWindow: 200_000,
    inputCostPer1M: 0.8,
    outputCostPer1M: 4,
    free: false,
    ...fast,
  },
  {
    provider: 'openrouter' as ProviderName,
    id: 'openai/gpt-4o',
    label: 'GPT-4o (OpenRouter)',
    contextWindow: 128_000,
    inputCostPer1M: 2.5,
    outputCostPer1M: 10,
    free: false,
  },
  {
    provider: 'openrouter' as ProviderName,
    id: 'openai/gpt-4o-mini',
    label: 'GPT-4o Mini (OpenRouter)',
    contextWindow: 128_000,
    inputCostPer1M: 0.15,
    outputCostPer1M: 0.6,
    free: false,
    ...fast,
  },
  {
    provider: 'openrouter' as ProviderName,
    id: 'google/gemini-pro-1.5',
    label: 'Gemini Pro 1.5 (OpenRouter)',
    contextWindow: 2_097_152,
    inputCostPer1M: 1.25,
    outputCostPer1M: 5,
    free: false,
  },
  {
    provider: 'openrouter' as ProviderName,
    id: 'meta-llama/llama-3.1-405b-instruct',
    label: 'Llama 3.1 405B (OpenRouter)',
    contextWindow: 128_000,
    inputCostPer1M: 3.5,
    outputCostPer1M: 3.5,
    free: false,
  },
  {
    provider: 'openrouter' as ProviderName,
    id: 'meta-llama/llama-3.1-70b-instruct',
    label: 'Llama 3.1 70B (OpenRouter)',
    contextWindow: 128_000,
    inputCostPer1M: 0.9,
    outputCostPer1M: 0.9,
    free: false,
  },
  {
    provider: 'openrouter' as ProviderName,
    id: 'qwen/qwen-2.5-72b-instruct',
    label: 'Qwen 2.5 72B (OpenRouter)',
    contextWindow: 32_768,
    inputCostPer1M: 0.9,
    outputCostPer1M: 0.9,
    free: false,
  },
  {
    provider: 'openrouter' as ProviderName,
    id: 'deepseek/deepseek-chat',
    label: 'DeepSeek Chat (OpenRouter)',
    contextWindow: 64_000,
    inputCostPer1M: 0.14,
    outputCostPer1M: 0.28,
    free: false,
  },
  {
    provider: 'openrouter' as ProviderName,
    id: 'deepseek/deepseek-coder',
    label: 'DeepSeek Coder (OpenRouter)',
    contextWindow: 64_000,
    inputCostPer1M: 0.14,
    outputCostPer1M: 0.28,
    free: false,
  },
  {
    provider: 'openrouter' as ProviderName,
    id: 'mistralai/mistral-large',
    label: 'Mistral Large (OpenRouter)',
    contextWindow: 128_000,
    inputCostPer1M: 2,
    outputCostPer1M: 6,
    free: false,
  },
  {
    provider: 'openrouter' as ProviderName,
    id: 'mistralai/mistral-nemo',
    label: 'Mistral Nemo (OpenRouter)',
    contextWindow: 128_000,
    inputCostPer1M: 0.15,
    outputCostPer1M: 0.15,
    free: false,
    ...fast,
  },
  {
    provider: 'openrouter' as ProviderName,
    id: 'cohere/command-r-plus',
    label: 'Command R+ (OpenRouter)',
    contextWindow: 128_000,
    inputCostPer1M: 3,
    outputCostPer1M: 15,
    free: false,
  },
  {
    provider: 'openrouter' as ProviderName,
    id: 'cohere/command-r',
    label: 'Command R (OpenRouter)',
    contextWindow: 128_000,
    inputCostPer1M: 0.5,
    outputCostPer1M: 1.5,
    free: false,
  },
  {
    provider: 'openrouter' as ProviderName,
    id: 'x-ai/grok-2-1212',
    label: 'Grok 2 (OpenRouter)',
    contextWindow: 131_072,
    inputCostPer1M: 2,
    outputCostPer1M: 10,
    free: false,
  },
  {
    provider: 'openrouter' as ProviderName,
    id: 'x-ai/grok-2-vision-1212',
    label: 'Grok 2 Vision (OpenRouter)',
    contextWindow: 32_768,
    inputCostPer1M: 2,
    outputCostPer1M: 10,
    free: false,
  },
  {
    provider: 'openrouter' as ProviderName,
    id: 'perplexity/pplx-7b-chat',
    label: 'Perplexity 7B (OpenRouter)',
    contextWindow: 8_192,
    inputCostPer1M: 0.2,
    outputCostPer1M: 0.2,
    free: false,
    ...fast,
  },
  {
    provider: 'openrouter' as ProviderName,
    id: 'perplexity/pplx-70b-chat',
    label: 'Perplexity 70B (OpenRouter)',
    contextWindow: 128_000,
    inputCostPer1M: 1,
    outputCostPer1M: 1,
    free: false,
  },
  {
    provider: 'openrouter' as ProviderName,
    id: 'openai/o1',
    label: 'OpenAI o1 (OpenRouter)',
    contextWindow: 128_000,
    inputCostPer1M: 15,
    outputCostPer1M: 60,
    free: false,
    ...reasoning,
  },
  {
    provider: 'openrouter' as ProviderName,
    id: 'openai/o1-mini',
    label: 'OpenAI o1-mini (OpenRouter)',
    contextWindow: 128_000,
    inputCostPer1M: 3,
    outputCostPer1M: 12,
    free: false,
    ...fast,
  },
];
